## makeCacheMatrix sets the inverse of a matrix to NULL when it is called directly
## it has four sub functions that do 
## set(), get(), setinverse() and getinverse() respectively
## cacheSolve takes an object returned by makeCacheMatrix and returns
## cached inverse of a matrix if it is not NULL
## computes and sets the cached value of a matrix otherwise
## example usage and sample output noted below:
## > a <- makeCacheMatrix(matrix(3:6, nrow=2, ncol=2))
## > cacheSolve(a)
## [,1] [,2]
## [1,]   -3  2.5
## [2,]    2 -1.5
## > cacheSolve(a)
## getting cached data
## [,1] [,2]
## [1,]   -3  2.5
## [2,]    2 -1.5

## makeCacheMatrix
## sets the inverse to NULL and retuns and object with four functions containing the matrix object
## this function has four subfunctions
## set -> that sets the value of a passed in matrix
## get -> gets the value of the set matrix
## setinverse -> sets the inverse value of a matrix that is already computed
## getinverse -> gets the cached value of the inverse of a matrix

makeCacheMatrix <- function(x = matrix()) {
  inverse <- NULL
  set <- function(y) {
    x <<- y
    inverse <<- NULL
  }
  get <- function() x
  setinverse <- function(inv) inverse <<- inv
  getinverse <- function() inverse
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)

}


## cacheSolve
## this object takes in an object generated by calling makeCacheMatrix and
## returns the inverse of the matrix if it is present in the cache
## if not, it computes the inverse and stores the inverse of the matrix
## for future use

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  inverse <- x$getinverse()
  if(!is.null(inverse)) {
    message("getting cached data")
    return(inverse)
  }
  data <- x$get()
  inverse <- solve(data, ...)
  x$setinverse(inverse)
  inverse
}


